server:
  port: 8282

spring:
#  main:
#    allow-circular-references: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service
      auto-index-creation: true

#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG


